spring:

 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cmq?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  username: root
  password: 1234

path:
 filePath: E:\\test

mybatis:
 mapper-locations: classpath:mapper/*Mapper.xml


 #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 #    database-platform: com.yangyu.util.MySQL5InnoDBDialectUtf8mb4

#logging:
#  level:
#    root: info
#    com.blog.blog: debug
#  file:
#    name: log/blog-dev.log
server:
 port: 8080